---
title: "Question 2 Analysis"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(fs)
library(ggplot2)
library(dplyr)
library(ggridges)
library(forcats)
library(scales)
library(viridis)
library(tagger)
library(colorspace)
library(RColorBrewer)
```

```{r theme}
ggplot2::theme_set(ggplot2::theme_minimal())

```

```{r}
superbowl<- read.csv("data/superbowl.csv")
```


```{r}
superbowl <- superbowl %>%
  mutate(ratio = like_count / (like_count + dislike_count),
         interactions = like_count + dislike_count + comment_count)
```


```{r}

outliers <- boxplot.stats(superbowl$view_count)$out


superbowl_no_outliers <- superbowl %>%
  filter((view_count %in% outliers))


quantile(superbowl_no_outliers$view_count,na.rm = TRUE)
  
```

```{r official-outliers list}
boxplot.stats(superbowl$view_count)$out
  
```


```{r}
superbowl <-superbowl %>%
  mutate(view_category = case_when(
    view_count < 4000 ~ "Few",
    view_count >=4000 & view_count < 30000 ~ "Some",
    view_count >= 30000 &view_count < 90000 ~ "Moderate",
    view_count >= 90000 &view_count < 500000 ~ "Many",
    view_count >= 500000 &view_count < 10000000 ~ "High",
    TRUE ~ "Viral"
  ))
```


```{r}
superbowl %>%
  mutate(Views = fct_relevel(
    view_category, "Viral", "High", "Many", "Moderate","Some","Few"
  )) %>%
ggplot(aes(x = ratio, y = Views, fill = Views)) +
  geom_density_ridges(scale = 1, show.legend = TRUE) +
  coord_cartesian(xlim = c(0.5, 1.0)) +
  scale_fill_discrete_sequential(palette = "Greens", order = c(6:1),
                                  labels = c("10M+", "500k to 10M", 
                                            "90K to 500K", "30K to 90K", 
                                            "4k to 30K", "Less than 4K")) +
  scale_x_continuous(expand = c(0, 0.1), labels = scales::percent_format(accuracy = 1)) +
  scale_y_discrete(expand = expand_scale(mult = c(0, .4))) +
  labs(
    title = "Youtube Superbowl Ads and Like Percentages",
    x = "Like Percentage",
    y = "Views Category",
    caption = "Source: FiveThirtyEight") +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_ridges() +
  theme(
    plot.title = element_text(hjust = .4, vjust = 2),
    plot.caption = element_text(hjust = 1.41),
    axis.title.x = element_text(hjust = .4), 
    axis.title.y = element_text(hjust = .38, vjust = 2))
```

```{r}
superbowl %>%
  group_by(view_category) %>%
  select(interactions)
```

```{r}
superbowl %>%
  group_by(view_category) %>%
  filter(!is.na(interactions)) %>%
  summarise(vti = sum(view_count) / sum(interactions))
```

```{r}
global_labeller=  <- labeller(
  view_category = capitalize,
  conservation = conservation_status,
  conservation2 = label_wrap_gen(10),
  .default = label_both
)
```




```{r }
superbowl%>%
  mutate(view_category = paste(view_category, "Views"))%>%
   mutate(view_category = fct_relevel(
    view_category, "Few Views","Some Views","Moderate Views","Many Views", "High Views",  "Viral Views" 
  ))%>%
ggplot(aes(x=view_count, y=interactions))+
    geom_area(aes(fill = view_category, alpha=0.5), show.legend = NULL)+
  geom_line()+
  facet_wrap(vars(view_category),  
             scales ="free",
             nrow = 3,
             strip.position = "top",
             labeller= labeller("label_both")) +
	scale_y_continuous(label = label_number_si()) +
  scale_x_continuous(label = label_number_si()) +
  labs(x = "View Count", y ="Number of Interactions", title ="Assessing Superbowl Ads Interactions",
       subtitle ="Interactions is defined by sum of \nlikes, dislikes and comments on a video",
       caption ="Number on Each Panel represents \nthe View To Interations Ratio of that view category") +
  theme(panel.grid.minor = element_blank(),
        strip.background = element_rect(colour = "black"),
        strip.placement = "inside",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        panel.spacing = unit(1.4, "lines"),
        plot.caption = element_text(color = "blue", size = 8, hjust =0.5),
        plot.caption.position = "panel",
        axis.text.x = NULL) +
  scale_fill_viridis(discrete = T)
```




